version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qresume
    ports:
      - "3306:3306"
    networks:
      - app-network

  qresume-app:
    build: .
    environment:
      - DB_HOST=db  # Ensure the app is pointing to the 'db' service name
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=qresume
      - QR_CODE_DIR=/app/qrcodes  # Define the QR code directory in the container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    # volumes:
    #   - "D:/Project/QResume/backend/qrcodes:/app/qrcodes"  # Map the Windows directory to the container
    volumes:
      - ./qrcodes:/app/qrcodes:rw


networks:
  app-network:
    driver: bridge
