version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qresume
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  qresume-app:
    build: .
    environment:
      - DB_HOST=dpg-cuerr83tq21c73emuta0-a  # Ensure the app is pointing to the 'db' service name
      - DB_PORT=5432  # Updated to PostgreSQL default port
      - DB_USER=postgres  # Updated to match PostgreSQL user
      - DB_PASSWORD=ydbCmI7NGgMcTFR6xUVWdJYjPzYiyNfD
      - DB_NAME=qresume
      - QR_CODE_DIR=/app/qrcodes  # Define the QR code directory in the container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./qrcodes:/app/qrcodes:rw

networks:
  app-network:
    driver: bridge
